name: build application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: npm

      - name: setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: "10.2.2"
          token: ${{ secrets.SQLTWO}}

      - name: setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: install amplify
        run: npm install -g @aws-amplify/cli

      - name: init amplify
        run: |
          amplify init --amplify '{
            "projectName": "sqltwo",
            "envName": "dev",
            "defaultEditor": "code",
            "framework": "reactnative",
            "language": "javascript"
          }' --yes --envName dev

      - name: setup the environment
        run: amplify env checkout dev

      - name: configure amplify
        run: amplify pull --appId "d30lo7dj5z84bu" --envName dev --yes

      - name: install dependencies
        run: npm ci

      - name: generate amplify outputs
        run: npx ampx generate outputs --app-id "d30lo7dj5z84bu" --branch dev --format json --out-dir . --yes

      - name: deploy on amplify
        run: amplify push --yes

      - name: build the application
        run: eas build --platform android --profile preview --non-interactive
